# Docker Compose Version
version: '3'
services:
    
    # Notebooks for Apache Spark - See:
    # https://github.com/jupyter/docker-stacks
    notebooks:
        image: anthonyrawlinsuom/lfmc-notebooks
        networks:
            - frontend
        ports:
          - "8888:8888"
          - "4040-4080:4040-4080"
        volumes:
          - /media/arawlins/Work/LFMC/lfmc-notebooks/notebooks:/home/jovyan/work/notebooks/
    
    # MongoDB image
    nosql:
        image: anthonyrawlinsuom/lfmc-mongodb
        # build: lfmc-mongodb
        networks:
          - middleware
        ports:
          - "27017:27017"
          - "28017:28017"
        volumes:
          - /media/arawlins/Work/NFSexports/Index/mongodb:/var/lib/mongodb
        restart: always
    
    # Node-RED
    pipeline:
        image: anthonyrawlinsuom/lfmc-pipeline
        # build: lfmc-pipeline
        restart: on-failure
        networks:
          - frontend
          - middleware
          - backend
        ports:
          - "1880:1880"
        depends_on:
          - nosql
    
    # PostGIS
    postgis:
        image: kartoza/postgis:9.4-2.1
        networks:
          - middleware
        ports:
          - "5432:5432"
    
    # GeoMESA
    geomesa:
        image: quay.io/geomesa/geoserver:geomesa-1.3.2-accumulo-1.7.3
        restart: on-failure
        networks:
          - frontend
          - middleware
        volumes:
          - /media/arawlins/Backup/DataSources/geomesa_data:/opt/geoserver/data_dir
        ports:
          - "9090:9090"
    
    # GeoServer
    geoserver:
        image: anthonyrawlinsuom/lfmc-geoserver
        # build: lfmc-geoserver
        restart: on-failure
        networks:
          - frontend
          - middleware
        ports:
          - "8080:8080"
        volumes:
          - /media/arawlins/Work/NFSexports/Spatial/geoserver_data:/opt/geoserver/data_dir
        depends_on:
          - postgis
    
    # Hadoop
    hdfs-name:
        image: quay.io/geomesa/hdfs:geomesa-1.3.2-accumulo-1.7.3
        command: name
        networks:
          - backend
        environment:
          HADOOP_MASTER_ADDRESS: hdfs-name
        ports:
          - "50070:50070"
    
    hdfs-data:
        image: quay.io/geomesa/hdfs:geomesa-1.3.2-accumulo-1.7.3
        command: data
        networks:
          - backend
        environment:
          HADOOP_MASTER_ADDRESS: hdfs-name
        depends_on:
          - hdfs-name
    
    # ZooKeeper
    zookeeper:
        image: quay.io/geomesa/zookeeper:latest
        networks:
          - backend
        ports:
          - "2181:2181"
    
    # Accumulo
    accumulo-master:
      image: quay.io/geomesa/accumulo-geomesa:geomesa-1.3.2-accumulo-1.7.3
      command: master --auto-init
      networks:
        - backend
        - middleware
      environment:
        HADOOP_MASTER_ADDRESS: hdfs-name
        ZOOKEEPERS: zookeeper
        ACCUMULO_PASSWORD: GisPwd
      depends_on:
        - zookeeper
    
    accumulo-monitor:
        image: quay.io/geomesa/accumulo-geomesa:geomesa-1.3.2-accumulo-1.7.3
        command: monitor
        networks:
          - backend
        environment:
          HADOOP_MASTER_ADDRESS: hdfs-name
          ZOOKEEPERS: zookeeper
        ports:
          - "9995:9995"
          - "50095:50095"
        depends_on:
          - zookeeper
          - accumulo-master
    
    accumulo-tserver:
        image: quay.io/geomesa/accumulo-geomesa:geomesa-1.3.2-accumulo-1.7.3
        command: tserver
        networks:
          - backend
        environment:
          HADOOP_MASTER_ADDRESS: hdfs-name
          ZOOKEEPERS: zookeeper
        depends_on:
          - zookeeper
          - accumulo-master
    
    # LFMCv1 API
    api:
        image: anthonyrawlinsuom/lfmc-api
        # build: lfmc-api
        restart: on-failure
        # deploy:
        #     mode: replicated
        #     replicas: 3
        #     endpoint_mode: dnsrr
        networks:
          - middleware
        ports:
          - "8002:8002"
        volumes:
          - /media/arawlins/Backups/DataSources/geoserver_data/FuelModels/:/FuelModels/
        depends_on:
          - pipeline
          - geoserver
    
    # LFMCv1 Website #NodeJS #Angular4
    # webserver:
    #     image: anthonyrawlinsuom/lfmc-staging
    #     build: lfmc-staging
    #     restart: on-failure
    #     # deploy:
    #     #    endpoint_mode: vip
    #     #    replicas: 5
    #     networks:
    #       - frontend
    #       - middleware
    #     ports:
    #       - "3000:3000"
    #     depends_on:
    #       - api
    #       - geoserver
    
    # ReadTheDocs
    documentation:
        # image: anthonyrawlinsuom/lfmc-docs
        image: anthonyrawlinsuom/lfmc-docs
        command: serve -a 0.0.0.0:8000
        restart: on-failure
        networks:
          - frontend
        ports:
          - "8000:8000"

volumes:
    docs_dir:
        

networks:
    middleware:
        driver: bridge
        ipam:
            driver: default

    frontend:
        driver: bridge
        ipam:
            driver: default
    backend:
        driver: bridge
        ipam:
            driver: default
