# Docker Compose Version
version: '3.3'
services:
    
    # For specific information on setting file upload size on a per-Virtual host
    # basis please see: https://github.com/schmunk42/nginx-proxy#proxy-wide
    proxy:
        image: jwilder/nginx-proxy:latest
        ports:
          - "80:80"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - /Work/LFMC/proxy-config:/etc/nginx/vhost.d:ro
        networks:
          - frontend
    
    # Notebooks for Apache Spark - See:
    # https://github.com/jupyter/docker-stacks
    notebooks:
        image: anthonyrawlinsuom/lfmc-notebooks
        networks:
            - frontend
        ports:
          - "8888:8888"
          - "4040-4080:4040-4080"
        volumes:
          - /Work/LFMC/lfmc-notebooks/notebooks:/home/jovyan/work/notebooks/
          - /Scratch/DataSources/geoserver_data/FuelModels/:/home/jovyan/work/notebooks/FuelModels/
        environment:
          - VIRTUAL_HOST=notebooks.landscapefuelmoisture.bushfirebehaviour.net.au
          - VIRTUAL_PORT=8888
    
    # MongoDB image
    nosql:
        image: anthonyrawlinsuom/lfmc-mongodb
        # build: lfmc-mongodb
        networks:
          - middleware
          - frontend
        ports:
          - "27017:27017"
          - "28017:28017"
        volumes:
          - /Work/Index/mongodb:/var/lib/mongodb
        restart: always
        environment:
          - VIRTUAL_HOST=nosql.landscapefuelmoisture.bushfirebehaviour.net.au
          - VIRTUAL_PORT=27017
    
    # Node-RED
    pipeline:
        image: anthonyrawlinsuom/lfmc-pipeline
        # build: lfmc-pipeline
        restart: on-failure
        networks:
          - frontend
          - middleware
          - backend
        ports:
            - "1880:1880"
        depends_on:
          - nosql
          - simplifyr
        volumes:
          - /Scratch/DataSources/geoserver_data/FuelModels/Weather:/mnt/data_dir
          - /Scratch/DataSources/geoserver_data/FuelModels/AWRA-L:/mnt/awra_dir
          - /Scratch/DataSources/geoserver_data/FuelModels/queries:/mnt/queries
        environment:
          - VIRTUAL_HOST=pipeline.landscapefuelmoisture.bushfirebehaviour.net.au
          - VIRTUAL_PORT=1880
    
    # PostGIS
    postgis:
        image: kartoza/postgis:9.4-2.1
        networks:
          - middleware
        ports:
          - "5432:5432"
        environment:
          - VIRTUAL_HOST=postgis.landscapefuelmoisture.bushfirebehaviour.net.au
    
    # GeoServer
    geoserver:
        image: anthonyrawlinsuom/lfmc-geoserver
        # build: lfmc-geoserver
        restart: on-failure
        networks:
          - frontend
          - middleware
        volumes:
          - /Scratch/DataSources/geoserver_data:/opt/geoserver/data_dir
        depends_on:
          - postgis
        environment:
          - VIRTUAL_HOST=geoserver.landscapefuelmoisture.bushfirebehaviour.net.au
          - VIRTUAL_PORT=8080
    
    # LFMCv1 API
    api:
        image: anthonyrawlinsuom/lfmc-api
        restart: on-failure
        networks:
          - frontend
          - middleware
        volumes:
          - /Scratch/DataSources/geoserver_data/FuelModels/:/FuelModels/
        depends_on:
          - pipeline
          - geoserver
        environment:
          - VIRTUAL_HOST=api.landscapefuelmoisture.bushfirebehaviour.net.au
          - VIRTUAL_PORT=8002
    
    # LFMCv1 Website #NodeJS #Angular4
    webserver:
        image: anthonyrawlinsuom/lfmc-staging:latest
        restart: on-failure
        command: node app.js
        networks:
          - frontend
          - middleware
        depends_on:
          - api
          - geoserver
        environment:
          - VIRTUAL_HOST=landscapefuelmoisture.bushfirebehaviour.net.au
          - VIRTUAL_PORT=3000
          
    # LFMCv1 Website Development
    # development:
    #     image: anthonyrawlinsuom/lfmc-staging:latest
    #     restart: on-failure
    #     command: npm start
    #     # deploy:
    #     #    endpoint_mode: vip
    #     #    replicas: 5
    #     networks:
    #       - frontend
    #       - middleware
    #     depends_on:
    #       - api
    #       - geoserver
    #     environment:
    #       - VIRTUAL_HOST=dev.landscapefuelmoisture.bushfirebehaviour.net.au
    #       - VIRTUAL_PORT=4200
    
    # ReadTheDocs
    documentation:
        # image: anthonyrawlinsuom/lfmc-docs
        image: anthonyrawlinsuom/lfmc-docs
        command: serve -a 0.0.0.0:8001
        restart: on-failure
        networks:
          - frontend
        environment:
          - VIRTUAL_HOST=documentation.landscapefuelmoisture.bushfirebehaviour.net.au
          - VIRTUAL_PORT=8001

    simplifyr:
        image: anthonyrawlinsuom/lfmc-simplifyr:latest
        volumes:
          - /Scratch/DataSources/geoserver_data/FuelModels/queries:/home/docker/rserve/data:ro
        networks:
          - frontend
        environment:
          - VIRTUAL_HOST=simplifyr.landscapefuelmoisture.bushfirebehaviour.net.au
          - VIRTUAL_PORT=8003
          
    cdn:
        build: docker-nginx-simple
        restart: always
        networks:
          - frontend
        volumes:
          - /Scratch/DataSources/geoserver_data/FuelModels/queries:/var/www:ro
        depends_on:
          - webserver
        environment:
          - VIRTUAL_HOST=cdn.landscapefuelmoisture.bushfirebehaviour.net.au
          - VIRTUAL_PORT=8088
          - PORT=8088
      
volumes:
    docs_dir:
        

networks:
    middleware:
        driver: bridge
        ipam:
            driver: default

    frontend:
        driver: bridge
        ipam:
            driver: default
    backend:
        driver: bridge
        ipam:
            driver: default
