# Docker Compose Version
version: '2'
services:
    
    # MongoDB image
    nosql:
        image: anthonyrawlinsuom/lfmc-mongodb
        ports:
          - 27017:27017
        volumes:
          - /srv/docker/mongodb:/var/lib/mongodb
        restart: always
    
    # Node-RED
    pipeline:
        image: anthonyrawlinsuom/lfmc-pipeline
        ports:
          - 1880:1880
        depends_on:
          - nosql
    
    # PostGIS
    postgis:
        image: kartoza/postgis:9.4-2.1
        ports:
          - 5432:5432
    
    # GeoMESA / GeoServer
    geoserver:
        image: anthonyrawlinsuom/lfmc-geoserver
        ports:
          - 9090:9090
        volumes:
          - /media/arawlins/Backups/DataSources/geoserver_data:/opt/geoserver/data_dir
        depends_on:
          - postgis
    
    # Hadoop
    hdfs-name:
        image: quay.io/geomesa/hdfs:geomesa-1.3.2-accumulo-1.7.3
        command: name
        environment:
          HADOOP_MASTER_ADDRESS: hdfs-name
        ports:
          - 50070:50070
    
    hdfs-data:
        image: quay.io/geomesa/hdfs:geomesa-1.3.2-accumulo-1.7.3
        command: data
        environment:
          HADOOP_MASTER_ADDRESS: hdfs-name
        depends_on:
          - hdfs-name
    
    # ZooKeeper
    zookeeper:
        image: quay.io/geomesa/zookeeper:latest
        ports:
          - 2181:2181
    
    # Accumulo
    accumulo-master:
      image: quay.io/geomesa/accumulo-geomesa:geomesa-1.3.2-accumulo-1.7.3
      command: master --auto-init
      environment:
        HADOOP_MASTER_ADDRESS: hdfs-name
        ZOOKEEPERS: zookeeper
        ACCUMULO_PASSWORD: GisPwd
      depends_on:
        - zookeeper
    
    accumulo-monitor:
        image: quay.io/geomesa/accumulo-geomesa:geomesa-1.3.2-accumulo-1.7.3
        command: monitor
        environment:
          HADOOP_MASTER_ADDRESS: hdfs-name
          ZOOKEEPERS: zookeeper
        ports:
          - 9995:9995
          - 50095:50095
        depends_on:
          - zookeeper
          - accumulo-master
    
    accumulo-tserver:
        image: quay.io/geomesa/accumulo-geomesa:geomesa-1.3.2-accumulo-1.7.3
        command: tserver
        environment:
          HADOOP_MASTER_ADDRESS: hdfs-name
          ZOOKEEPERS: zookeeper
        depends_on:
          - zookeeper
          - accumulo-master
    
    # LFMCv1 API
    api:
        image: anthonyrawlinsuom/lfmc-api
        ports:
          - 8000:8000
        depends_on:
          - pipeline
          - geoserver
    
    # LFMCv1 Website #NodeJS #Angular4
    webserver:
        image: anthonyrawlinsuom/lfmc-staging
        ports:
          - 80:4200
        depends_on:
          - api
    
    # ReadTheDocs
    docs:
        image: anthonyrawlinsuom/lfmc-docs
        ports:
          - 8001:8001
