apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: accumulo-master
  name: accumulo-master
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: accumulo-master
    spec:
      containers:
      - args:
        - master
        - --auto-init
        env:
        - name: ACCUMULO_PASSWORD
          value: GisPwd
        - name: HADOOP_MASTER_ADDRESS
          value: hdfs-name
        - name: ZOOKEEPERS
          value: zookeeper
        image: quay.io/geomesa/accumulo-geomesa:geomesa-1.3.2-accumulo-1.7.3
        name: accumulo-master
        resources: {}
      restartPolicy: Always
status: {}
