apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  containers:
  - image: anthonyrawlinsuom/lfmc-api
    name: api
    ports:
    - containerPort: 8002
    resources: {}
  restartPolicy: OnFailure
status: {}
