apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: documentation
  name: documentation
spec:
  containers:
  - args:
    - serve
    - -a
    - 0.0.0.0:8000
    image: anthonyrawlinsuom/lfmc-docs
    name: documentation
    ports:
    - containerPort: 8000
    resources: {}
  restartPolicy: OnFailure
status: {}
