apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pipeline
  name: pipeline
spec:
  containers:
  - image: anthonyrawlinsuom/lfmc-pipeline
    name: pipeline
    ports:
    - containerPort: 1880
    resources: {}
  restartPolicy: OnFailure
status: {}
