apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift --file docker-compose.yml convert
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: accumulo-master
  name: accumulo-master
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: accumulo-master
status:
  loadBalancer: {}
