apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift --file docker-compose.yml convert
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: accumulo-monitor
  name: accumulo-monitor
spec:
  replicas: 1
  selector:
    io.kompose.service: accumulo-monitor
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: accumulo-monitor
    spec:
      containers:
      - args:
        - monitor
        env:
        - name: HADOOP_MASTER_ADDRESS
          value: hdfs-name
        - name: ZOOKEEPERS
          value: zookeeper
        image: ' '
        name: accumulo-monitor
        ports:
        - containerPort: 9995
        - containerPort: 50095
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - accumulo-monitor
      from:
        kind: ImageStreamTag
        name: accumulo-monitor:geomesa-1.3.2-accumulo-1.7.3
    type: ImageChange
status: {}
