apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: geoserver
  name: geoserver
spec:
  containers:
  - image: anthonyrawlinsuom/lfmc-geoserver
    name: geoserver
    ports:
    - containerPort: 8080
    resources: {}
    volumeMounts:
    - mountPath: /opt/geoserver/data_dir
      name: geoserver-claim0
  restartPolicy: OnFailure
  volumes:
  - name: geoserver-claim0
    persistentVolumeClaim:
      claimName: geoserver-claim0
status: {}
