apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nosql
  name: nosql
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: anthonyrawlinsuom/lfmc-mongodb
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
