apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift --file docker-compose.yml convert
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: postgis
  name: postgis
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: postgis
status:
  loadBalancer: {}
