apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift --file docker-compose.yml convert
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: postgis
  name: postgis
spec:
  replicas: 1
  selector:
    io.kompose.service: postgis
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgis
    spec:
      containers:
      - image: ' '
        name: postgis
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - postgis
      from:
        kind: ImageStreamTag
        name: postgis:9.4-2.1
    type: ImageChange
status: {}
